# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 11:36
from __future__ import unicode_literals

import Survey.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer_1', models.CharField(max_length=255)),
                ('answer_2', models.CharField(max_length=255)),
                ('answer_3', models.CharField(max_length=255)),
                ('votes_1', models.IntegerField(default=0)),
                ('votes_2', models.IntegerField(default=0)),
                ('votes_3', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedSurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.IntegerField(default=0)),
                ('choice', models.CharField(max_length=255)),
                ('subscription_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_title', models.CharField(max_length=120)),
                ('survey_description', models.CharField(max_length=255)),
            ],
            options={
                'permissions': (('can_vote', 'Vote questions in the survey'), ('can_report', 'Can see the results of the survey')),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=120)),
                ('topic_description', models.CharField(max_length=255)),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_card', models.CharField(max_length=8, unique=True, verbose_name='identity card')),
                ('id_card_scan', models.FileField(blank=True, upload_to='documents/', validators=[Survey.validators.validate_file_extension], verbose_name='Scansione ID Card')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('comune', models.CharField(blank=True, max_length=30, verbose_name='comune')),
                ('provincia', models.CharField(blank=True, max_length=30, verbose_name='provincia')),
                ('indirizzo', models.CharField(blank=True, max_length=120, verbose_name='indirizzo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscribedsurveyquestion',
            name='surveyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.Survey'),
        ),
        migrations.AddField(
            model_name='subscribedsurveyquestion',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.Topic'),
        ),
        migrations.AlterUniqueTogether(
            name='subscribedsurveyquestion',
            unique_together=set([('username', 'surveyId', 'questionId')]),
        ),
    ]
